### PR TITLE
Refactor guts into gatt_core

### PR DESCRIPTION
**Pull request by richo**
This gives you enough primitives to run the gatt_client programmatically
without a repl

r? @mikeryan 

(Totally untested, wrote it on a flight to india)

### CODE REVIEW

**Comment by mikeryan** [comment]
I'm good with this in principle and I think it's the Right Thing. I ran into one issue trying to run it:

```
Traceback (most recent call last):
  File "/usr/local/bin/gatt_client", line 9, in <module>
    load_entry_point('PyBT==0.1', 'console_scripts', 'gatt_client')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File ".../PyBT/PyBT/gattclient.py", line 138, in <module>
    'onconnect': CommandModule.onconnect,
AttributeError: type object 'CommandModule' has no attribute 'onconnect'
```

Looks like you simply forgot to move `onconnect` into gatt_core. It seems like the onconnect stuff belongs in gattclient proper (since it relates mostly to an interactive client). There are some onconnect hooks in the guts of gatt_core, not sure what the right way to move these into gattclient is.

**Comment by richo** [comment]
Hah. Knew I forgot something (literally did not even try to test it)

I can on principle pull the I connect stuff out, but I think in that case
we'd need a blocking variant of connect() to make it useful again (since
there's stuff you don't want to do until you're connected )

**Comment by mikeryan** [comment]
What's the oncommand stuff I see? This points strongly to a half-implemented onconnect solution coded in a fit of drunkenness.

**Comment by richo** [comment]
Modulo a rebase to make the commit messages not terribad I think this is at least comparable to what was. Want to test?

r? @mikeryan

**Comment by mikeryan** [comment]
gatt_client still freezes up when I attempt to ctrl-C scan. I have to kill it with `kill`.

```
>>> scan
^CKeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/bin/gatt_client", line 9, in <module>
    load_entry_point('PyBT==0.1', 'console_scripts', 'gatt_client')()
  File ".../PyBT/PyBT/gattclient.py", line 198, in main
    gevent.wait()
  File "/usr/lib/python2.7/dist-packages/gevent/hub.py", line 642, in wait
    return get_hub().join(timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/gevent/hub.py", line 394, in join
    waiter.get()
  File "/usr/lib/python2.7/dist-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()
  File "/usr/lib/python2.7/dist-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
KeyboardInterrupt

^C^C
^C
^C
```

If I actually see a device, I get a second exception before the final KeyboardInterrupt exception.

```
>>> scan
Saw f7:59:89:9e:cd:ec (random)
GAP: Flags: ['LE General Discoverable Mode', 'BR/EDR Not Supported'], Complete List of 16-bit Service Class UUIDs: ['feed']
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File ".../PyBT/PyBT/gatt_core.py", line 55, in run
    event = self.conn.central.stack.handle_data()
  File ".../PyBT/PyBT/stack.py", line 100, in handle_data
    p = self.s.recv()
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/bluetooth.py", line 654, in recv
    return HCI_Hdr(self.ins.recv(x))
KeyboardInterrupt
<Greenlet at 0x7f269c32e410: <bound method SocketHandler.run of <PyBT.gatt_core.SocketHandler object at 0x7f269b8cf2d0>>> failed with KeyboardInterrupt

Traceback (most recent call last):
  File "/usr/local/bin/gatt_client", line 9, in <module>
    load_entry_point('PyBT==0.1', 'console_scripts', 'gatt_client')()
  File ".../PyBT/PyBT/gattclient.py", line 198, in main
    gevent.wait()
  File "/usr/lib/python2.7/dist-packages/gevent/hub.py", line 642, in wait
    return get_hub().join(timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/gevent/hub.py", line 394, in join
    waiter.get()
  File "/usr/lib/python2.7/dist-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()
  File "/usr/lib/python2.7/dist-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
KeyboardInterrupt
```

**Comment by richo** [comment]
Did it actually die gracefully before? I seem to remember having to ctrl C
it a lot of times before it died (albeit without a stack trace).

In my testing, it did actually die if you left it alone for a while. In any
case, I can poke at it, but I'm kiiinda of the opinion that it should just
land if the core functionality works, and worse case I'll just bind the INT
handler to have a stab at taking the Central down and then SIGKILLing
itself into oblivion. I want to work on other stuff on top of it, and I'm
not really confident enough about what machinery gevent is using under the
hood to do that right now.

**Comment by mikeryan** [comment]
I'm willing to merge this as-is if it makes your life easier, and I can poke again at the gevent guts. It's gross and long-term it's probably best to ditch it. I'm quite certain it behaved properly before, but we've mashed up a lot of guts.

**Pull request merged**
